#pragma once

// Baked-in NAM models for the Phase 0 spike (see nam_spike.h). The .cpp is generated by
// scripts/nam/gen_baked_models.py from NeuralAmpModelerCore's example models.

namespace deluge::nam_spike {

// A2-Lite: real trained capture (the A2-Lite submodel of NeuralAmpModelerCore's
// example_models/A2.nam, MIT licensed). This is the model used for live processing.
extern const char kNamA2LiteConfigJson[];
extern const float kNamA2LiteWeights[];
extern const int kNamA2LiteNumWeights;

// A1-Nano: synthetic model (correct architecture, deterministic random weights).
// Benchmark timing only - it does not model any real device.
extern const char kNamA1NanoConfigJson[];
extern const float kNamA1NanoWeights[];
extern const int kNamA1NanoNumWeights;

} // namespace deluge::nam_spike
