#!/usr/bin/env python3
"""Generate the baked NAM models for the Deluge Phase 0 spike.

Outputs:
  models/a2lite.nam, models/a1nano.nam        -- standalone files for native validation
  generated/nam_baked_models.cpp               -- firmware source (config strings + weight arrays)
"""

import json
import random
import sys
from pathlib import Path

HERE = Path(__file__).parent
NAM_REPO = HERE / "NeuralAmpModelerCore"
sys.path.insert(0, str(NAM_REPO / "tools"))
import create_wavenet

OUT_MODELS = HERE / "models"
OUT_GEN = HERE / "generated"
OUT_MODELS.mkdir(exist_ok=True)
OUT_GEN.mkdir(exist_ok=True)

# ---------------------------------------------------------------- A2-Lite ----
packed = json.loads((NAM_REPO / "example_models" / "A2.nam").read_text())
a2lite = packed["config"]["submodels"][0]["model"]
assert a2lite["architecture"] == "WaveNet"
a2lite_weights = a2lite["weights"]
print(f"A2-Lite: {len(a2lite_weights)} weights, sr={a2lite['sample_rate']}")
(OUT_MODELS / "a2lite.nam").write_text(json.dumps(a2lite))


# ---------------------------------------------------------------- A1-Nano ----
def a1_layer(input_size, channels, head_size, dilations, head_bias):
    return {
        "input_size": input_size,
        "condition_size": 1,
        "head_size": head_size,
        "channels": channels,
        "kernel_size": 3,
        "dilations": dilations,
        "activation": "Tanh",
        "gated": False,
        "head_bias": head_bias,
    }


nano_config = {
    "layers": [
        a1_layer(1, 4, 2, [1, 2, 4, 8, 16, 32, 64], False),
        a1_layer(4, 2, 1, [128, 256, 512, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512], True),
    ],
    "head": None,
    "head_scale": 0.02,
}
create_wavenet.validate_config(nano_config)
n_nano = sum(
    create_wavenet.count_layer_array_weights(lc) for lc in nano_config["layers"]
)
n_nano += 1  # head_scale weight
print(f"A1-Nano: computed {n_nano} weights")

rng = random.Random(0xDE1B6E)
nano_weights = [round(rng.uniform(-0.25, 0.25), 6) for _ in range(n_nano)]
a1nano = {
    "version": "0.5.4",
    "architecture": "WaveNet",
    "config": nano_config,
    "weights": nano_weights,
    "sample_rate": 48000,
}
(OUT_MODELS / "a1nano.nam").write_text(json.dumps(a1nano))


# ------------------------------------------------------------ firmware C++ ----
def config_json_string(model):
    """The 'config' block only, weights stripped, compact."""
    return json.dumps(model["config"], separators=(",", ":"))


def float_array(name, values):
    body = ",".join(f"{v:.9g}f" if v else "0.f" for v in values)
    return f"const float {name}[{len(values)}] = {{{body}}};\n"


def c_string_literal(name, s):
    # Raw string literal: no escaping needed for JSON content
    assert ')nam"' not in s
    return f'const char {name}[] = R"nam({s})nam";\n'


cpp = [
    "// Generated by gen_baked_models.py -- do not edit by hand.",
    "// Baked NAM models for the Phase 0 benchmark spike.",
    "//",
    "// kNamA2LiteConfigJson/Weights: the A2-Lite submodel of NeuralAmpModelerCore's",
    "// example_models/A2.nam (MIT), a real trained capture (48kHz, ~1.9k params).",
    '// kNamA1NanoConfigJson/Weights: an A1 "nano" architecture with deterministic',
    "// random weights -- for timing only, it does not model any real device.",
    '#include "processing/nam/nam_baked_models.h"',
    "",
    "namespace deluge::nam_spike {",
    "",
    c_string_literal("kNamA2LiteConfigJson", config_json_string(a2lite)),
    float_array("kNamA2LiteWeights", a2lite_weights),
    f"const int kNamA2LiteNumWeights = {len(a2lite_weights)};",
    "",
    c_string_literal("kNamA1NanoConfigJson", config_json_string(a1nano)),
    float_array("kNamA1NanoWeights", nano_weights),
    f"const int kNamA1NanoNumWeights = {len(nano_weights)};",
    "",
    "} // namespace deluge::nam_spike",
    "",
]
(OUT_GEN / "nam_baked_models.cpp").write_text("\n".join(cpp))
print(f"wrote {OUT_GEN / 'nam_baked_models.cpp'}")
