#!/usr/bin/env bash
# Build the spike plugin blob with the same target flags as the firmware, and prove it is
# relocation-free. Outputs: spike.dlp (drop into PLUGINS/ on the card) and spike_blob.h (embedded copy).
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$(git rev-parse --show-toplevel)"
BIN="$ROOT/toolchain/v22/darwin-arm64/arm-none-eabi-gcc/bin"
FLAGS="-mcpu=cortex-a9 -mfpu=neon -mfloat-abi=hard -mthumb -O2 -fPIC -mpic-data-is-text-relative \
       -ffreestanding -nostdlib -fno-builtin -fno-exceptions -fno-asynchronous-unwind-tables \
       -ffunction-sections -fdata-sections -Wall"
"$BIN/arm-none-eabi-gcc" $FLAGS -c blob_main.c -o spike.o
"$BIN/arm-none-eabi-gcc" $FLAGS -Wl,-T,plugin.ld -Wl,--gc-sections -Wl,-Map,spike.map -o spike.elf spike.o
echo "== undefined symbols (must be none):"; "$BIN/arm-none-eabi-nm" -u spike.elf || true
echo "== relocations (must be none):"; "$BIN/arm-none-eabi-readelf" -r spike.elf | tail -n +1
"$BIN/arm-none-eabi-objcopy" -O binary spike.elf spike.dlp
"$BIN/arm-none-eabi-objdump" -d spike.elf | head -60
ls -la spike.dlp
python3 - <<'PY'
data = open("spike.dlp", "rb").read()
assert data[:4] == b"DLP1", data[:4]
lines = ", ".join(f"0x{b:02x}" for b in data)
open("spike_blob.h", "w").write(
    "// Generated by build.sh from spike.dlp - do not edit.\n#pragma once\n#include <stdint.h>\n"
    f"static const uint32_t kSpikeBlobSize = {len(data)};\n"
    f"static const uint8_t kSpikeBlob[{len(data)}] = {{{lines}}};\n")
print("spike_blob.h:", len(data), "bytes")
PY
